//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Category_Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Weight { get; set; }
        public string In_Box_Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public Nullable<int> Modified_By { get; set; }
    }
}
